Move status bar item to the right
zeithaste/cursorCharCode pull request #9
Opened 2022-12-08 23:32 UTC by ygoe

The character info should now be next to the line/column display (number value by try & error & retry same & other error...). The left side of the status bar is already pretty crowded with project actions and the right side seems more for the editor itself, so I find it more appropriate to put it there.

2022-12-08 23:33 UTC, ygoe commented
Yes, I said "it couldn't be any better" in my updated review, but I still found this minor thing... 😉 Could change it myself this time.

2022-12-09 06:33 UTC, zeithaste commented
Thanks, this looks good to me. I'll test it a bit and publish the extension update in the evening, if everything works well.

2022-12-09 21:06 UTC, zeithaste requested changes
Everything seems to work as it should.
Could you please update the [changelog](https://github.com/ygoe/cursorCharCode/blob/ec037c0d85205c080919c92a9b4256e991c8df96/CHANGELOG.md?plain=1#L3) and bump the [version](https://github.com/ygoe/cursorCharCode/blob/ec037c0d85205c080919c92a9b4256e991c8df96/package.json#L5) to 0.2.2?

2022-12-09 21:06 UTC, zeithaste commented on src/extension.ts
> +}
```suggestion
}

```

2022-12-14 19:44 UTC, ygoe commented
I can do that. But it seems that GitHub has lost me here. While I could suggest the initial change easily, I have now no more edit methods here, so I first need to find this branch, check it out and set up everything for local work. Pull requests and working in other people's repositories is always a pain.

2022-12-14 19:55 UTC, zeithaste commented
Oh, I can push the needed changes into [your branch](https://github.com/ygoe/cursorCharCode/tree/patch-1) then.

2022-12-14 20:06 UTC, ygoe commented
Go ahead, let's see how it works.

2022-12-14 20:09 UTC, zeithaste approved these changes

2022-12-14 20:10 UTC, merged

2022-12-14 20:18 UTC, zeithaste commented
The updated extension should be available shortly.

2022-12-14 21:28 UTC, ygoe commented
Thank you! I found these notification e-mails after I saw that this extension needs a reload. ;-)